version: "3.7"

services:
  nginx:
    build:
      context: './nginx'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./logs/nginx:/var/log/nginx
    networks:
      - backend
    depends_on:
      - api
      - app
    restart: always

  app:
    build:
      context: './app'
    environment:
      - ENV=${ENV}
    networks:
      - backend

  db:
    image: mongo:4.0
    volumes:
     - db-data:/data/db
    networks:
      - backend

  migrations:
    build:
      context: './migrations'
    depends_on:
      - db
    networks:
      - backend

  api:
    build:
      context: './api'
    depends_on:
      - db
    networks:
      - backend
    environment:
      - ENV=${ENV}
    restart: always

networks:
  backend:

volumes:
  db-data:
